/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export type PostType = { 'important' : null } |
  { 'daily' : null };
export interface PostView {
  'id' : bigint,
  'postType' : PostType,
  'title' : string,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
}
export interface RegistrationData {
  'age' : bigint,
  'username' : string,
  'gmail' : string,
}
export type RegistrationResult = { 'invalidEmail' : null } |
  { 'other' : null } |
  { 'usernameAlreadyExists' : null } |
  { 'registrationSuccessful' : null };
export type Time = bigint;
export interface User {
  'id' : bigint,
  'age' : bigint,
  'username' : string,
  'gmail' : string,
  'registrationTime' : Time,
}
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUsernameAvailability' : ActorMethod<[string], boolean>,
  'createPost' : ActorMethod<[string, string, PostType], bigint>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllPosts' : ActorMethod<[], Array<PostView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getImportantPosts' : ActorMethod<[], Array<PostView>>,
  'getPost' : ActorMethod<[bigint], PostView>,
  'getPostLikes' : ActorMethod<[bigint], Array<Principal>>,
  'getPostsByUser' : ActorMethod<[Principal], Array<PostView>>,
  'getProfileId' : ActorMethod<[Principal], UserProfile>,
  'getRecentPosts' : ActorMethod<[], Array<PostView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[RegistrationData], RegistrationResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPosts' : ActorMethod<[string], Array<PostView>>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'updateComment' : ActorMethod<[bigint, string], undefined>,
  'updatePost' : ActorMethod<[bigint, string, string, PostType], undefined>,
  'updateProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];