/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostType = IDL.Variant({
  'important' : IDL.Null,
  'daily' : IDL.Null,
});
export const Time = IDL.Int;
export const PostView = IDL.Record({
  'id' : IDL.Nat,
  'postType' : PostType,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'username' : IDL.Text,
  'gmail' : IDL.Text,
  'registrationTime' : Time,
});
export const RegistrationData = IDL.Record({
  'age' : IDL.Nat,
  'username' : IDL.Text,
  'gmail' : IDL.Text,
});
export const RegistrationResult = IDL.Variant({
  'invalidEmail' : IDL.Null,
  'other' : IDL.Null,
  'usernameAlreadyExists' : IDL.Null,
  'registrationSuccessful' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, PostType], [IDL.Nat], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getImportantPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [PostView], ['query']),
  'getPostLikes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
  'getProfileId' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getRecentPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([RegistrationData], [RegistrationResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, PostType], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostType = IDL.Variant({ 'important' : IDL.Null, 'daily' : IDL.Null });
  const Time = IDL.Int;
  const PostView = IDL.Record({
    'id' : IDL.Nat,
    'postType' : PostType,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'username' : IDL.Text,
    'gmail' : IDL.Text,
    'registrationTime' : Time,
  });
  const RegistrationData = IDL.Record({
    'age' : IDL.Nat,
    'username' : IDL.Text,
    'gmail' : IDL.Text,
  });
  const RegistrationResult = IDL.Variant({
    'invalidEmail' : IDL.Null,
    'other' : IDL.Null,
    'usernameAlreadyExists' : IDL.Null,
    'registrationSuccessful' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsernameAvailability' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, PostType], [IDL.Nat], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getImportantPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [PostView], ['query']),
    'getPostLikes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Principal)], ['query']),
    'getPostsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getProfileId' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getRecentPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([RegistrationData], [RegistrationResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PostView)], ['query']),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePost' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, PostType], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };